-- 37_fn_bulk_insert_assets.sql
-- Atomic bulk asset insert RPC.
-- Mirrors fn_bulk_insert_employees pattern: single PL/pgSQL transaction, TABLE return type.
-- Calls fn_create_asset_with_log per row (which auto-generates asset_tag via fn_next_asset_tag).
-- If ANY row fails the entire function raises an exception → Postgres rolls back automatically.

set search_path = public;

create or replace function fn_bulk_insert_assets(p_rows jsonb)
returns table (payload jsonb)
language plpgsql
security definer
set search_path = public
as $$
declare
  el         jsonb;
  v_result   jsonb;
  v_inserted int  := 0;
  v_max      int  := 500;
  v_status   text;
begin
  -- Auth guards
  if auth.uid() is null then
    return query select jsonb_build_object('ok', false, 'message', 'Not authenticated');
    return;
  end if;

  if not fn_is_admin_or_it_ops() then
    return query select jsonb_build_object('ok', false, 'message', 'Admin or IT Ops role required');
    return;
  end if;

  -- Input guards
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' then
    return query select jsonb_build_object('ok', false, 'message', 'Expected a JSON array of asset rows');
    return;
  end if;

  if jsonb_array_length(p_rows) = 0 then
    return query select jsonb_build_object('ok', false, 'message', 'No rows to import');
    return;
  end if;

  if jsonb_array_length(p_rows) > v_max then
    return query select jsonb_build_object(
      'ok',      false,
      'message', format('Too many rows (%s). Maximum is %s.', jsonb_array_length(p_rows), v_max)
    );
    return;
  end if;

  -- Insert loop — single transaction; any raise propagates and rolls back everything
  for el in select jsonb_array_elements(p_rows)
  loop
    v_status := coalesce(nullif(trim(coalesce(el->>'status', '')), ''), 'in_stock');

    v_result := fn_create_asset_with_log(
      p_asset_tag           := null,  -- auto-generated by fn_next_asset_tag
      p_category_slug       := nullif(trim(coalesce(el->>'category_slug',       '')), ''),
      p_category_name       := nullif(trim(coalesce(el->>'category_name',       '')), ''),
      p_manufacturer_name   := nullif(trim(coalesce(el->>'manufacturer_name',   '')), ''),
      p_model               := nullif(trim(coalesce(el->>'model',               '')), ''),
      p_serial_number       := nullif(trim(coalesce(el->>'serial_number',       '')), ''),
      p_location_code       := nullif(trim(coalesce(el->>'location_code',       '')), ''),
      p_location_name       := nullif(trim(coalesce(el->>'location_name',       '')), ''),
      p_status              := v_status::asset_status,
      p_purchase_date       := case
                                 when nullif(trim(coalesce(el->>'purchase_date', '')), '') is not null
                                 then (el->>'purchase_date')::date
                                 else null
                               end,
      p_warranty_expiry     := case
                                 when nullif(trim(coalesce(el->>'warranty_expiry', '')), '') is not null
                                 then (el->>'warranty_expiry')::date
                                 else null
                               end,
      p_custom_fields       := coalesce(el->'custom_fields', '{}'::jsonb),
      p_metadata            := coalesce(el->'metadata',      '{}'::jsonb),
      p_log_note            := 'Bulk import',
      p_qr_code             := null,
      p_actor_employee_code := null
    );

    if not coalesce((v_result->>'ok')::boolean, false) then
      -- raise rolls back the entire function (and all prior inserts in this call)
      raise exception 'Row % failed: %',
        v_inserted + 1,
        coalesce(v_result->>'message', 'Unknown error');
    end if;

    v_inserted := v_inserted + 1;
  end loop;

  return query
  select jsonb_build_object('ok', true, 'inserted', v_inserted);
end;
$$;

revoke all on function fn_bulk_insert_assets(jsonb) from public;
grant execute on function fn_bulk_insert_assets(jsonb) to authenticated, service_role;
